CREATE TABLE "SUBJECT" (
	"S_ID"	INTEGER,
	"CODE"	TEXT,
	"NAME"	TEXT,
	"COLOR"	TEXT,
	"CREATED_AT"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("S_ID" AUTOINCREMENT)
);

CREATE TABLE "NOTES" (
	"N_ID"	INTEGER,
	"CHAPTER"	INTEGER,
	"NAME"	TEXT,
	"FILE_PATH"	TEXT,
	"CREATED_AT"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"S_ID"	INTEGER,
	PRIMARY KEY("N_ID" AUTOINCREMENT),
	FOREIGN KEY("S_ID") REFERENCES "SUBJECT"("S_ID")
);

CREATE TABLE "TASK" (
	"T_ID"	INTEGER,
	"TITLE"	TEXT,
	"DUE_DATE"	TEXT,
	"COMPLETED"	INTEGER NOT NULL DEFAULT 0,
	"CREATED_AT"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"S_ID"	INTEGER,
	"C_ID"	TEXT,
	PRIMARY KEY("T_ID" AUTOINCREMENT),
	FOREIGN KEY("C_ID") REFERENCES "CATEGORY"("C_ID"),
	FOREIGN KEY("S_ID") REFERENCES "SUBJECT"("S_ID")
);

CREATE TABLE "CATEGORY" (
	"C_ID"	INTEGER,
	"CATEGORY"	TEXT,
	PRIMARY KEY("C_ID" AUTOINCREMENT)
);